create table "public"."subjects_suggestions" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "sender" uuid not null,
    "email" text,
    "created_at" timestamp with time zone default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone,
    "accepted" boolean
);


alter table "public"."subjects_suggestions" enable row level security;

CREATE UNIQUE INDEX subjects_suggestions_pkey ON public.subjects_suggestions USING btree (id);

alter table "public"."subjects_suggestions" add constraint "subjects_suggestions_pkey" PRIMARY KEY using index "subjects_suggestions_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.compound_search(listing record)
 RETURNS text
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
DECLARE
  profile_first_name TEXT;
  profile_last_name TEXT;
  profile_role TEXT;
  listing_title TEXT;
  listing_description TEXT;
  listing_hourly_price INT;
BEGIN
  -- Initialize listing fields to default values
  listing_title := '';
  listing_description := '';
  listing_hourly_price := 0;

  -- Retrieve the profile information
  SELECT p.first_name, p.last_name, p.role
  INTO profile_first_name, profile_last_name, profile_role
  FROM profiles p
  WHERE p.id = listing.profile;

  -- Retrieve the title, description, and hourly_price from the listings table for visible listings
  SELECT l.title, l.description, l.hourly_price 
  INTO listing_title, listing_description, listing_hourly_price
  FROM listings l
  WHERE l.id = listing.id AND l.visible = TRUE;

  -- Check if the role is 'teacher' and if the listing is visible
  IF profile_role = 'teacher' AND listing_title IS NOT NULL THEN
    RETURN profile_first_name || ' ' || profile_last_name || ' ' ||
           COALESCE(listing_title, '') || ' ' || 
           COALESCE(listing_description, '') || ' ' ||
           COALESCE(listing_hourly_price::TEXT, '');
  ELSE
    RETURN NULL; -- or you can return '' for an empty string
  END IF;
END;

$function$
;

grant delete on table "public"."subjects_suggestions" to "anon";

grant insert on table "public"."subjects_suggestions" to "anon";

grant references on table "public"."subjects_suggestions" to "anon";

grant select on table "public"."subjects_suggestions" to "anon";

grant trigger on table "public"."subjects_suggestions" to "anon";

grant truncate on table "public"."subjects_suggestions" to "anon";

grant update on table "public"."subjects_suggestions" to "anon";

grant delete on table "public"."subjects_suggestions" to "authenticated";

grant insert on table "public"."subjects_suggestions" to "authenticated";

grant references on table "public"."subjects_suggestions" to "authenticated";

grant select on table "public"."subjects_suggestions" to "authenticated";

grant trigger on table "public"."subjects_suggestions" to "authenticated";

grant truncate on table "public"."subjects_suggestions" to "authenticated";

grant update on table "public"."subjects_suggestions" to "authenticated";

grant delete on table "public"."subjects_suggestions" to "service_role";

grant insert on table "public"."subjects_suggestions" to "service_role";

grant references on table "public"."subjects_suggestions" to "service_role";

grant select on table "public"."subjects_suggestions" to "service_role";

grant trigger on table "public"."subjects_suggestions" to "service_role";

grant truncate on table "public"."subjects_suggestions" to "service_role";

grant update on table "public"."subjects_suggestions" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."subjects_suggestions"
as permissive
for insert
to authenticated
with check (true);



